spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017  
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:5000/uaa/oauth2/jwks
      client:
        registration:
          statistics-service: 
            provider: spring
            client-id: statistics-service
            client-secret: statistics_secret
            authorization-grant-type: client_credentials
            scope: server
        provider:
          spring: 
            authorization-uri: http://localhost:5000/uaa/oauth2/authorize
            token-uri: http://localhost:5000/uaa/oauth2/token
            jwk-set-uri: http://localhost:5000/uaa/oauth2/jwks


feign:
  circuitbreaker:
    enabled: false
  compression:
    request:
      enabled: true
      mime-types: application/json
    response:
      enabled: true
  client.config.default:
    connectTimeout: 1000
    readTimeout: 60000
    decode404: false      

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://api.exchangeratesapi.io