logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current

spring:
  rabbitmq:
    host: localhost
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true        

        