server:
  port: 4000
       
spring:
  cloud:
    loadbalancer:
      ribbon: 
        enabled: false 
    gateway:
      routes:
      - id: account-service
        uri: lb://account-service
        predicates:
        - Path=/accounts/**
      - id: auth-service
        uri: http://localhost:5000
        predicates:
        - Path=/uaa/**
      - id: statistics-service
        uri: lb://statistics-service
        predicates:
        - Path=/statistics/**
      - id: notification-service
        uri: lb://notification-service
        predicates:
        - Path=/notifications/**         
      