server:
  servlet:
    context-path: /accounts
  port: 6001 

spring:
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true        
  data:
    mongodb:
      host: localhost
      username: user
      password: password
      database: piggymetrics
      port: 27017 
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:5000/uaa/oauth2/jwks
      client:
        registration:
          account-service: 
            provider: spring
            client-id: account-service
            client-secret: account_secret
            authorization-grant-type: client_credentials
            scope: server
        provider:
          spring: 
            authorization-uri: http://localhost:5000/uaa/oauth2/authorize
            token-uri: http://localhost:5000/uaa/oauth2/token
            jwk-set-uri: http://localhost:5000/uaa/oauth2/jwks